"""Initial migration

Revision ID: 0108b6eaf432
Revises: 6bf9c05cee3d
Create Date: 2025-10-12 12:23:38.811426

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '0108b6eaf432'
down_revision: Union[str, Sequence[str], None] = '6bf9c05cee3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
