"""Initial migration

Revision ID: 56bbe5b70fbe
Revises: 
Create Date: 2025-10-12 02:47:48.780157

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '56bbe5b70fbe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
