"""Add authentication and documents

Revision ID: 6bf9c05cee3d
Revises: 56bbe5b70fbe
Create Date: 2025-10-12 02:53:12.021238

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '6bf9c05cee3d'
down_revision: Union[str, Sequence[str], None] = '56bbe5b70fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
