"""Add file_name, file_size, file_type to documents

Revision ID: 95786d196571
Revises: 9283c8de598c
Create Date: 2025-10-12 15:36:20.397991

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '95786d196571'
down_revision: Union[str, Sequence[str], None] = '9283c8de598c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
